@startuml 
left to right direction

actor Pasajero as P
actor Tripulación as T
actor "Personal de Tierra" as PT

rectangle "App Móvil" {
    P --> (Consulta de Vuelos)
    P --> (Check-in y Embarque Digital)
    P --> (Integración de Servicios)
    T --> (Actualizaciones de Itinerarios)
    PT --> (Asignación de Puertas y Horarios)
    
    (Consulta de Vuelos) --> (Notificaciones en Tiempo Real)
    (Actualizaciones de Itinerarios) --> (Notificaciones en Tiempo Real)
    (Asignación de Puertas y Horarios) --> (Notificaciones en Tiempo Real)
    
    (Notificaciones en Tiempo Real) --> (Información Actualizada)
    (Check-in y Embarque Digital) --> (Información Actualizada)
    (Integración de Servicios) --> (Información Actualizada)
}

@enduml
